Fix custom_shader_pipelined example shader (#2992)
## Objective

Looking though the new pipelined example I stumbled on an issue with the example shader :

```
Oct 20 12:38:44.891  INFO bevy_render2::renderer: AdapterInfo { name: "Intel(R) UHD Graphics 620 (KBL GT2)", vendor: 32902, device: 22807, device_type: IntegratedGpu, backend: Vulkan }
Oct 20 12:38:44.894  INFO naga::back::spv::writer: Skip function Some("fetch_point_shadow")    
Oct 20 12:38:44.894  INFO naga::back::spv::writer: Skip function Some("fetch_directional_shadow")    
Oct 20 12:38:44.898 ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
    Global variable [1] 'view' is invalid
    Type isn't compatible with the storage class
```

## Solution

added `<uniform>` here and there.
Note : my current mastery of shaders is about 2 days old, so this still kinda look likes wizardry