shader_prepass example: disable MSAA for maximum compatibility  (#8504)
# Objective


Since #8446, example `shader_prepass` logs the following error on my mac
m1:
```
ERROR bevy_render::render_resource::pipeline_cache: failed to process shader:
error: Entry point fragment at Fragment is invalid
 = Argument 1 varying error
 = Capability MULTISAMPLED_SHADING is not supported
```
The example display the 3d scene but doesn't change with the preps
selected

Maybe related to this update in naga:
https://github.com/gfx-rs/naga/commit/cc3a8ac73773e2223c3d45fbc1b22607026e2ec0

## Solution

- Disable MSAA in the example, and check if it's enabled in the shader